### PR TITLE
Update 05-Review_Webpage_Content_for_Information_Leakage.md

### PR DESCRIPTION
**Pull request by charlesteets**
changed "hardcod" to "hardcode" and changed "owner must to pay for that" to "owner must pay for that"

### CODE REVIEW

**Comment by kingthorin** [comment]
@charlesteets do you intent to submit this via the proper repo?

**Comment by charlesteets** [comment]
The typos I corrected were already corrected in the proper repo, I will
unrequest this change

**Comment by kingthorin** [comment]
Thanks. 

The Stable deployment will be replaced when 4.3 or 5.0 is released. Stable is currently identical to 4.2, since 4.2 was released with the issues then it's fine as-is. (From my perspective.)

**Comment by kingthorin** [comment]
Closing per earlier comments.

**Pull request closed without merging**
